import "server-only";
import { Pdf, type TextOptions } from "./pdf-lite.mjs";
import type { FilingPeriod, ReviewPackage } from "./types";

/**
 * The review package as a PDF a person can send.
 *
 * The package already renders itself as markdown, and markdown is the wrong
 * thing to hand a tax manager: it arrives as a wall of asterisks and pipes in
 * whatever reads it, and a document full of figures somebody has to act on
 * should not make them decode it first. So the same content is laid out —
 * paginated, with the tables aligned and the money right-aligned in a
 * monospaced column.
 *
 * ## DRAFT is not decoration
 *
 * Every page carries the word, in the header and again in the footer, and the
 * cover says it in a box before anything else. This is the one thing about
 * this document that must survive being printed, forwarded, photographed and
 * read out of order. A page of Schedule C figures with no marking on it looks
 * exactly like a finished return, and the whole product exists to stop a
 * person filing something no human checked.
 *
 * ## Why it is built by hand
 *
 * `pdf-lite` is already in this repo, already has the font metrics, and
 * already produces the fixture corpus. A rendering dependency would add a
 * headless browser or a layout engine to a server whose only other job is
 * reading documents, in exchange for typography nobody is going to notice on a
 * document that exists to be read once and acted on.
 */

const W = 612;
const H = 792;
const M = 54;
const R = W - M;
const TOP = 96;
const BOTTOM = H - 64;

const INK: [number, number, number] = [0.09, 0.09, 0.11];
const SOFT: [number, number, number] = [0.42, 0.44, 0.5];
const HAIR: [number, number, number] = [0.85, 0.86, 0.88];
const BRAND: [number, number, number] = [0.996, 0.004, 0];

type Line =
  | { kind: "h1" | "h2" | "h3"; text: string }
  | { kind: "text"; text: string }
  | { kind: "bullet"; text: string }
  | { kind: "rule" }
  | { kind: "gap" }
  | { kind: "row"; cells: string[]; head?: boolean };

/**
 * Enough markdown to render what this app writes, and no more.
 *
 * Not a general parser and not trying to be. The input is generated by
 * `renderPackageMarkdown` a few functions away, so the grammar is known: ATX
 * headings, pipe tables, dashes for bullets, horizontal rules, paragraphs.
 * Anything unrecognised falls through as plain text, which is the right
 * failure — a stray token renders as itself rather than vanishing from a
 * document somebody is about to rely on.
 */
function parse(markdown: string): Line[] {
  const lines: Line[] = [];

  for (const raw of markdown.split("\n")) {
    const line = raw.trimEnd();

    if (!line.trim()) {
      lines.push({ kind: "gap" });
      continue;
    }
    if (/^\s*([-*_])\1{2,}\s*$/.test(line)) {
      lines.push({ kind: "rule" });
      continue;
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line);
    if (heading) {
      const depth = heading[1].length;
      lines.push({ kind: depth === 1 ? "h1" : depth === 2 ? "h2" : "h3", text: strip(heading[2]) });
      continue;
    }

    if (line.trim().startsWith("|") && line.includes("|")) {
      const cells = line.trim().replace(/^\||\|$/g, "").split("|").map((cell) => strip(cell.trim()));
      // The `|---|---|` separator is structure, not content. Marking the row
      // before it as the header is what lets the renderer rule underneath it.
      if (cells.every((cell) => /^:?-{2,}:?$/.test(cell))) {
        const previous = lines[lines.length - 1];
        if (previous?.kind === "row") previous.head = true;
        continue;
      }
      lines.push({ kind: "row", cells });
      continue;
    }

    const bullet = /^\s*[-*+]\s+(.*)$/.exec(line);
    if (bullet) {
      lines.push({ kind: "bullet", text: strip(bullet[1]) });
      continue;
    }

    lines.push({ kind: "text", text: strip(line) });
  }

  return lines;
}

/** Drop the markers. Bold and italic have nowhere to go in this layout. */
function strip(value: string): string {
  return value
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/(^|\s)\*(?!\s)(.+?)\*/g, "$1$2")
    .replace(/`(.+?)`/g, "$1")
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1")
    .trim();
}

/** Greedy wrap against the real font metrics, so nothing overruns the margin. */
function wrap(doc: Pdf, text: string, width: number, opts: TextOptions): string[] {
  if (!text) return [""];
  const words = text.split(/\s+/);
  const out: string[] = [];
  let line = "";

  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (doc.widthOf(candidate, opts) <= width || !line) {
      line = candidate;
    } else {
      out.push(line);
      line = word;
    }
  }
  if (line) out.push(line);
  return out;
}

/** A figure sets in mono so columns of them line up down the page. */
function isMoney(cell: string): boolean {
  return /^[-(]?[$€£¥]?\s?[\d,]+\.\d{2}\)?$/.test(cell.trim()) || /^\d+$/.test(cell.trim());
}

export function renderPackagePdf(input: {
  pkg: ReviewPackage;
  period: FilingPeriod;
  markdown: string;
  preparedBy: string;
}): Buffer {
  const doc = new Pdf({
    width: W,
    height: H,
    producer: "DO-09 Tax Document Preparation Assistant",
    creationDate: Pdf.stamp(),
  });
  const { pkg, period, markdown } = input;

  let page = 0;
  let y = 0;

  const chrome = () => {
    page += 1;
    doc.page();

    doc.text(M, 44, "DO-09 · TAX DOCUMENT PREPARATION", {
      font: "Helvetica-Bold",
      size: 7.5,
      color: SOFT,
      charSpace: 1.1,
    });
    doc.textRight(R, 44, "DRAFT — NOT FILED", {
      font: "Helvetica-Bold",
      size: 7.5,
      color: BRAND,
      charSpace: 1.1,
    });
    doc.line(M, 56, R, 56, { color: HAIR, lineWidth: 0.6 });

    doc.line(M, BOTTOM + 22, R, BOTTOM + 22, { color: HAIR, lineWidth: 0.6 });
    doc.text(M, BOTTOM + 36, `${period.label} · ${period.entity} · DRAFT, nothing filed`, {
      size: 7.5,
      color: SOFT,
    });
    doc.textRight(R, BOTTOM + 36, `Page ${page}`, { size: 7.5, color: SOFT });

    y = TOP;
  };

  /** Start a new page when the next block would not fit whole. */
  const room = (needed: number) => {
    if (y + needed > BOTTOM) chrome();
  };

  chrome();

  /* ── Cover ──────────────────────────────────────────────────────────────
   * The counts come before the money, and that ordering is the argument the
   * whole package makes. A pack opening with "net profit $47,300" invites the
   * reader to trust it; one opening with "nine items need your decision"
   * tells them what they are actually holding.
   */
  doc.text(M, y + 12, "Review package", { font: "Helvetica-Bold", size: 24, color: INK });
  y += 30;
  doc.text(M, y + 12, `${period.label} · ${period.entity}`, { size: 12.5, color: SOFT });
  y += 26;
  doc.text(
    M,
    y + 12,
    `${period.start} to ${period.end} · ${period.basis} basis · ${period.currency} · ${period.jurisdiction}`,
    { size: 9.5, color: SOFT },
  );
  y += 30;

  doc.rect(M, y, R - M, 54, { fill: [1, 0.955, 0.95] });
  doc.text(M + 14, y + 21, "DRAFT — nothing here has been filed", {
    font: "Helvetica-Bold",
    size: 11,
    color: BRAND,
  });
  doc.text(
    M + 14,
    y + 39,
    "Every figure and every form is a draft prepared for review. No return was submitted or signed.",
    { size: 8.8, color: [0.5, 0.25, 0.25] },
  );
  y += 74;

  const stats: [string, string][] = [
    ["Documents", String(pkg.counts.documents)],
    ["Read", String(pkg.counts.extracted)],
    ["Unreadable", String(pkg.counts.unreadable)],
    ["Need a decision", String(pkg.counts.needsReview)],
    ["Open items", String(pkg.counts.openExceptions)],
  ];
  const cell = (R - M) / stats.length;
  stats.forEach(([label, value], i) => {
    const x = M + i * cell;
    doc.text(x, y + 10, label.toUpperCase(), { size: 6.8, color: SOFT, charSpace: 0.7 });
    doc.text(x, y + 30, value, {
      font: "Helvetica-Bold",
      size: 17,
      // The two counts that mean "a person still has to do something" are the
      // only ones coloured. A wall of uniformly styled numbers hides them.
      color: (label === "Need a decision" || label === "Open items") && value !== "0" ? BRAND : INK,
    });
  });
  y += 48;

  doc.line(M, y, R, y, { color: HAIR });
  y += 10;
  doc.text(M, y + 10, `Prepared by ${input.preparedBy} · assembled ${pkg.createdAt.slice(0, 10)}`, {
    size: 8.5,
    color: SOFT,
  });
  y += 34;

  /* ── Body ─────────────────────────────────────────────────────────────── */

  const blocks = parse(markdown);

  for (let i = 0; i < blocks.length; i += 1) {
    const block = blocks[i];

    if (block.kind === "gap") {
      y += 7;
      continue;
    }

    if (block.kind === "rule") {
      room(14);
      doc.line(M, y, R, y, { color: HAIR });
      y += 12;
      continue;
    }

    if (block.kind === "h1" || block.kind === "h2" || block.kind === "h3") {
      const size = block.kind === "h1" ? 15 : block.kind === "h2" ? 12.5 : 10.8;
      const opts: TextOptions = { font: "Helvetica-Bold", size, color: INK };
      const wrapped = wrap(doc, block.text, R - M, opts);

      // A heading is kept with the block under it. One stranded at the foot of
      // a page sends the reader looking for a section that starts overleaf.
      room(wrapped.length * (size + 4) + 34);
      y += block.kind === "h1" ? 12 : 8;
      for (const text of wrapped) {
        doc.text(M, y + size, text, opts);
        y += size + 4;
      }
      if (block.kind === "h1") {
        y += 4;
        doc.line(M, y, R, y, { color: HAIR });
      }
      y += 8;
      continue;
    }

    if (block.kind === "row") {
      /*
       * Tables are laid out as a unit, not row by row, because the column
       * widths depend on every row in the group. Measuring them one page at a
       * time would produce a table whose columns shift halfway down.
       */
      const rows: { cells: string[]; head?: boolean }[] = [];
      let j = i;
      while (j < blocks.length && blocks[j].kind === "row") {
        rows.push(blocks[j] as { cells: string[]; head?: boolean });
        j += 1;
      }
      i = j - 1;

      const columns = Math.max(...rows.map((r) => r.cells.length));
      const natural: number[] = [];
      for (let c = 0; c < columns; c += 1) {
        natural[c] = Math.max(
          ...rows.map((r) => doc.widthOf(r.cells[c] ?? "", { size: 8.6 })),
          24,
        );
      }
      const total = natural.reduce((a, b) => a + b, 0);
      const available = R - M - (columns - 1) * 10;
      const widths = natural.map((w) => (w / total) * available);

      // A money column reads right-aligned. Deciding per column rather than
      // per cell keeps a column of figures aligned even where one row holds an
      // em dash for a document nobody has read yet.
      const numeric = Array.from({ length: columns }, (_, c) =>
        rows.filter((r) => !r.head).some((r) => isMoney(r.cells[c] ?? "")),
      );

      room(28);
      for (const row of rows) {
        const opts: TextOptions = {
          size: 8.6,
          font: row.head ? "Helvetica-Bold" : "Helvetica",
          color: row.head ? INK : [0.2, 0.21, 0.24],
        };

        const heights = row.cells.map((text, c) =>
          wrap(doc, text, widths[c] ?? available, opts).length,
        );
        const tall = Math.max(1, ...heights);
        room(tall * 12 + 8);

        let x = M;
        row.cells.forEach((text, c) => {
          const width = widths[c] ?? available;
          const money = numeric[c] && !row.head;
          const style: TextOptions = money ? { ...opts, font: "Courier" } : opts;
          const parts = wrap(doc, text, width, style);
          parts.forEach((part, k) => {
            if (money) doc.textRight(x + width, y + 9 + k * 11, part, style);
            else doc.text(x, y + 9 + k * 11, part, style);
          });
          x += width + 10;
        });

        y += tall * 11 + 5;
        if (row.head) {
          doc.line(M, y - 1, R, y - 1, { color: HAIR });
          y += 3;
        }
      }
      y += 8;
      continue;
    }

    // Paragraphs and bullets.
    const bullet = block.kind === "bullet";
    const left = bullet ? M + 13 : M;
    const opts: TextOptions = { size: 9.4, color: [0.2, 0.21, 0.24] };
    const wrapped = wrap(doc, block.text, R - left, opts);

    room(wrapped.length * 13 + 4);
    if (bullet) doc.text(M + 3, y + 9, "·", { font: "Helvetica-Bold", size: 11, color: SOFT });
    for (const text of wrapped) {
      doc.text(left, y + 9, text, opts);
      y += 13;
    }
    y += 3;
  }

  return doc.toBuffer();
}

/** `2026-Q3-review-package-DRAFT.pdf`, safe on every filesystem. */
export function packageFilename(period: FilingPeriod): string {
  const slug = `${period.label} ${period.entity}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 70);
  return `${slug || "review-package"}-DRAFT.pdf`;
}
